import type { SongData } from "@pianojam/shared";
import { MIDI_MAX, MIDI_MIN, sanitizeSongData } from "@pianojam/shared";

/**
 * The bundled sample songs (generated by tools/generate-songs.mjs) and the
 * shared MIDI parsing path. Bundled picks and custom uploads both end up in
 * parseMidiBuffer, so they go through exactly the same loading flow.
 */

export interface BundledSong {
  id: string;
  title: string;
  url: string;
}

export const BUNDLED_SONGS: BundledSong[] = [
  { id: "twinkle", title: "Twinkle Twinkle Little Star", url: "/res/songs/twinkle.mid" },
  { id: "ode-to-joy", title: "Ode to Joy (Beethoven)", url: "/res/songs/ode-to-joy.mid" },
  { id: "fur-elise", title: "Fur Elise (Beethoven, opening)", url: "/res/songs/fur-elise.mid" },
  { id: "canon-in-d", title: "Canon in D (Pachelbel)", url: "/res/songs/canon-in-d.mid" },
];

/**
 * Parses a .mid file into the shared SongData shape: every track merged
 * into one stream (v1 has no track selection), notes outside the 88-key
 * range dropped, then normalized by the same sanitizer the server uses.
 */
export async function parseMidiBuffer(
  buffer: ArrayBuffer,
  fallbackTitle: string,
): Promise<SongData | null> {
  // Lazy import keeps the parser out of the main bundle; only the admin
  // loading a song pays for it.
  const { Midi } = await import("@tonejs/midi");
  let midi: InstanceType<typeof Midi>;
  try {
    midi = new Midi(buffer);
  } catch {
    return null;
  }
  const notes = midi.tracks
    .flatMap((track) => track.notes)
    .filter((n) => n.midi >= MIDI_MIN && n.midi <= MIDI_MAX)
    .map((n) => ({
      midi: n.midi,
      time: n.time,
      duration: n.duration,
      velocity: n.velocity,
    }));
  const title = midi.header.name?.trim() || fallbackTitle;
  return sanitizeSongData({ title, notes });
}
